name: Test-github-action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Run echo
        run: ech "Hello world"
  test:
    if: always()
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Run echo
        run: echo "In test job"     
